ACGN_Project/urls.py
from django.contrib import admin
from django.urls import path, include # 導入個人應用程式
from django.conf import settings
from django.conf.urls.static import static

from . import views  # 導入專案的 views.py(自己手動建的)

urlpatterns = [
    # 預設路徑(http://127.0.0.1:8000/)時
    # 去找專案資料夾下的views.py(自己手動建的)的 index 函數
    # path('', views.index),

    # 原路徑 - 後台管理頁面'登入頁面'
    # path('admin/', admin.site.urls, name='admin'),

    # http://127.0.0.1:8000/<str:template_name>.html 
    # 以確保操作index時其餘頁面都能正常連結到
    path('<str:template_name>.html', views.render_template, name='render_template'),
    
    # http://127.0.0.1:8000/Example_APP/ 
    # 假設我們各自導入自己的應用程式(Example_APP)個人操作的模樣
    path('Example_APP/', include('Example_APP.urls')),

    # admin-APP (後台管理者)
    # http://127.0.0.1:8000/admin/
    path('admin/', include('admins.urls')), # 包含 admin 的 URL
    # http://127.0.0.1:8000/admin/
    path('api_admin/', include('api_admin.urls')), # 包含 api_admin 的 URL

    # Member-APP (後台會員)
    # http://127.0.0.1:8000/admin/member/ 
    path('admin/member/', include('member.urls')), # 包含 member 的 URL
    # http://127.0.0.1:8000/admin/api_member/ 
    path('admin/api_member/', include('api_member.urls')),  # 包含 api_member 的 URL
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api_member/urls.py
from django.urls import path
from . import views  # 導入視圖

app_name = "api_member"
urlpatterns = [
    # http://127.0.0.1:8000/admin/api_member/
    path('', views.index, name="index"),


    # http://127.0.0.1:8000/api_member/register
    path('register/', views.register),
    # http://127.0.0.1:8000/api_member/checkname/
    path('checkname/', views.checkname ),
    # http://127.0.0.1:8000/api_member/checkphone/
    path('checkphone/', views.checkphone ),
    # http://127.0.0.1:8000/api_member/checkemail/
    path('checkemail/', views.checkemail ),
    # http://127.0.0.1:8000/api_member/checkpassword/
    path('checkpassword/', views.checkpassword ),
    # http://127.0.0.1:8000/api_member/search/
    path('search/', views.search, name='search' ),
    # http://127.0.0.1:8000/api_member/signup
    path('signup/', views.signup, name='signup'),
        # http://127.0.0.1:8000/api_member/personal/
    path('personal/', views.personal ),
    # http://127.0.0.1:8000/api_member/privacy_setting/
    path('privacy_setting/', views.privacy_setting, name="privacy_setting" ),


    # http://127.0.0.1:8000/api_member/send_reset_email/
    path('send_reset_email/', views.send_reset_email, name='send_reset_email'),
    # http://127.0.0.1:8000/api_member/request-verification/
    path('request-verification/', views.request_verification, name='request_verification'),
    # http://127.0.0.1:8000/api_member/send_verification_email/
    path('send_verification_email/', views.send_verification_email, name='send_verification_email'),
    # http://127.0.0.1:8000/api_member/verify_code/
    path('verify_code/', views.verify_code, name='verify_code'),
    # http://127.0.0.1:8000/api_member/reset_confirm
    path('reset_confirm/', views.reset_confirm, name='reset_confirm'),
    # http://127.0.0.1:8000/api_member/email_change/
    path('email_change/', views.email_change, name='email_change'),
    # http://127.0.0.1:8000/api_member/email_change_confirm/<str:token>/
    path('email_change_confirm/<str:token>/', views.email_change_confirm, name='email_change_confirm'),
    # http://127.0.0.1:8000/api_member/email_change_form/
    path('email_change_form/<str:code>/', views.email_change_form, name='email_change_form'),

    
    # http://127.0.0.1:8000/api_member/verify-email/
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),

    
    # http://127.0.0.1:8000/api_member/reset_email/
    path('reset_email/', views.reset_email, name='reset_email'),
    # http://127.0.0.1:8000/api_member/reconfirm_email/<str:token>/
    path('reconfirm_email/<str:token>/', views.reconfirm_email, name='reconfirm_email'),
    # http://127.0.0.1:8000/api_member/reset_phone/
    path('reset_phone/', views.reset_phone, name='reset_phone'),
    # http://127.0.0.1:8000/api_member/reconfirm_phone/<str:token>/
    path('reconfirm_phone/<str:token>/', views.reconfirm_phone, name='reconfirm_phone'),


    # http://127.0.0.1:8000/api_member/phone_change/
    path('phone_change/', views.phone_change, name='phone_change'),
    # http://127.0.0.1:8000/api_member/phone_change_confirm/<str:token>/
    path('phone_change_confirm/<str:token>/', views.phone_change_confirm, name='phone_change_confirm'),
    # http://127.0.0.1:8000/api_member/phone_change_form/<str:code>/
    path('phone_change_form/<str:code>/', views.phone_change_form, name='phone_change_form'),
]

member/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = 'member'
urlpatterns = [
    # http://127.0.0.1:8000/admin/member/
    path('', views.index, name="index" ),
    # http://127.0.0.1:8000/admin/member/404
    path('404/', views.page404, name="404" ),

    # http://127.0.0.1:8000/member/register
    path('register/', views.register, name="create" ),
    # http://127.0.0.1:8000/member/edit/
    path('edit/', views.edit, name="edit" ),
    # http://127.0.0.1:8000/member/delete/
    path('delete/<int:id>', views.delete, name="delete" ),
    
    # http://127.0.0.1:8000/member/hand_verify/
    path('hand_verify/', views.hand_verify, name="hand_verify" ),
    # http://127.0.0.1:8000/member/login/
    path('login/', views.login, name='login'),
    # http://127.0.0.1:8000/member/logout/
    path('logout/', views.logout, name='logout'),
    # http://127.0.0.1:8000/member/signup/
    path('signup/', views.signup, name="signup"),


    # http://127.0.0.1:8000/member/reset/
    path('reset/', views.reset, name="reset"),
    # http://127.0.0.1:8000/member/reset_confirm/
    path('reset_confirm/', views.reset_confirm, name="reset_confirm"),

    
    # http://127.0.0.1:8000/member/email_change/
    path('email_change/', views.email_change, name="email_change"),
    # http://127.0.0.1:8000/member/email_change_confirm/
    path('email_change_confirm/<str:uidb64>/<str:token>/', views.email_change_confirm, name='email_change_confirm'),
    # http://127.0.0.1:8000/member/email_reconfirm/
    path('email_reconfirm/<str:token>/', views.email_reconfirm, name='email_reconfirm'),
    # http://127.0.0.1:8000/member/phone_change/
    path('phone_change/', views.phone_change, name="phone_change"),
    # http://127.0.0.1:8000/member/phone_change_confirm/
    path('phone_change_confirm/<str:uidb64>/<str:token>/', views.phone_change_confirm, name='phone_change_confirm'),
    # http://127.0.0.1:8000/member/phone_reconfirm/
    path('phone_reconfirm/<str:token>/', views.phone_reconfirm, name='phone_reconfirm'),

    # http://127.0.0.1:8000/member/personal/
    path('personal/', views.personal, name="personal"),
    
    # # http://127.0.0.1:8000/member/verify-code/
    # path('verify-code/', views.verify_code, name='verify_code'),

    # http://127.0.0.1:8000/member/dashboard/
    path('dashboard/', views.dashboard, name='dashboard'),
]

member/templates/member/email_change_confirm.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>郵箱重設／Email Reset</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media"> 
	
	{% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
	

    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">
	
</head> 

<body class="app app-reset p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'member:reset' %}"><img class="logo-icon me-2" src="{% static 'member\images\app-logo.svg' %}" alt="logo"></a></div>
					
					<h2 class="auth-heading text-center mb-4">Email Reset／郵箱重設</h2>

					<div class="auth-intro mb-4 text-center">請於下方輸入您的新郵箱與密碼，以便為您重設。<br>
						Enter your new email and password below.<br> We'll reset you a new email.</div>
					<div class="auth-form-container text-left">
						
						<form class="auth-form resetpass-form" id="resetEmailForm" action="{% url 'api_member:email_change_confirm' token %}" method="POST">
							{% csrf_token %}                  
							<div class="email mb-3">
								<input type="hidden" id="oldEmailInput" name="oldEmail" value="{{ old_email }}">
								<label class="sr-only" for="InputEmail">新郵箱：</label>
								<input id="InputEmail" name="email" type="email" class="form-control login-email" placeholder="新郵箱" required>
								<label class="sr-only" for="PasswordCheck">密碼：</label>
								<input id="PasswordCheck" name="password" type="password" class="form-control login-password" placeholder="密碼" minlength="8" required>

								<div id="emailHelp" class="alert alert-warning" style="display: none;"></div>
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" id="submitCheck" class="btn app-btn-primary btn-block theme-btn mx-auto">修改郵箱</button>
							</div>
						</form>

						<div id="message" class="alert" style="display: none;"></div>

						<div class="auth-option text-center pt-5"><a class="app-link" href="{% url 'member:login' %}" >Log in／登入</a> <span class="px-2">|</span> <a class="app-link" href="{% url 'member:signup' %}" >Sign up／註冊</a></div>
					</div><!--//auth-form-container-->


			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-3.jpg' %}'); background-size: cover;">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->

	<script>
		const resetEmailForm = document.querySelector('#resetEmailForm');
		const messageDiv = document.querySelector('#message');
		const inputEmail = document.querySelector('#InputEmail');
		const passwordCheck = document.querySelector('#PasswordCheck');
		const emailHelp = document.querySelector('#emailHelp');
		const oldEmailInput = document.querySelector('#oldEmailInput');

		resetEmailForm.addEventListener('submit', async function(e) {
			e.preventDefault();

			const newEmail = inputEmail.value;
			const password = passwordCheck.value;
			const oldEmail = oldEmailInput.value;

			try {
				const response = await fetch('{% url "api_member:email_change_confirm" token %}', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify({
						email: newEmail,
						password: password,
						oldEmail: oldEmail
					})
				});

				const data = await response.json();
				messageDiv.textContent = data.message;
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert ' + (data.status === 'success' ? 'alert-success' : 'alert-danger');

				if (data.status === 'success') {
					setTimeout(() => {
						window.location.href = '{% url "member:login" %}';
					}, 5000);
				}
			} catch (error) {
				console.error('Error:', error);
				messageDiv.textContent = '發生錯誤，請稍後再試。';
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert alert-danger';
			}
		});
	</script>
</body>
</html> 

member/templates/member/email_change_form.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>郵箱重設／Email Reset</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media"> 
	
	{% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
	

    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">
	
</head> 

<body class="app app-reset p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'member:reset' %}"><img class="logo-icon me-2" src="{% static 'member\images\app-logo.svg' %}" alt="logo"></a></div>
					
					<h2 class="auth-heading text-center mb-4">Email Reset／郵箱重設</h2>

					<div class="auth-intro mb-4 text-center">請於下方輸入您的新郵箱與密碼，以便為您重設。<br>
						Enter your new email and password below.<br> We'll reset you a new email.</div>
					<div class="auth-form-container text-left">
						
						<form class="auth-form resetpass-form" id="resetEmailForm" action="{% url 'api_member:email_change_form' code %}" method="POST">
							{% csrf_token %}                  
							<div class="email mb-3">
								<input type="hidden" id="oldEmailInput" name="oldEmail" value="{{ old_email }}">
								<input type="hidden" id="codeInput" name="verification_code" value="{{ verification_code }}"> 
								<label class="sr-only" for="InputEmail">新郵箱：</label>
								<input id="InputEmail" name="email" type="email" class="form-control login-email" placeholder="新郵箱" required>
								<label class="sr-only" for="PasswordCheck">密碼：</label>
								<input id="PasswordCheck" name="password" type="password" class="form-control login-password" placeholder="密碼" minlength="8" required>

								<div id="emailHelp" class="alert alert-warning" style="display: none;"></div>
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" id="submitCheck" class="btn app-btn-primary btn-block theme-btn mx-auto">修改郵箱</button>
							</div>
						</form>

						<div id="message" class="alert" style="display: none;"></div>

						<div class="auth-option text-center pt-5"><a class="app-link" href="{% url 'member:login' %}" >Log in／登入</a> <span class="px-2">|</span> <a class="app-link" href="{% url 'member:signup' %}" >Sign up／註冊</a></div>
					</div><!--//auth-form-container-->


			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-3.jpg' %}'); background-size: cover;">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->

	<script>
		const resetEmailForm = document.querySelector('#resetEmailForm');
		const messageDiv = document.querySelector('#message');
		const inputEmail = document.querySelector('#InputEmail');
		const passwordCheck = document.querySelector('#PasswordCheck');
		const emailHelp = document.querySelector('#emailHelp');
		const oldEmailInput = document.querySelector('#oldEmailInput');
		const codeInput = document.querySelector('#codeInput');

		resetEmailForm.addEventListener('submit', async function(e) {
			e.preventDefault();

			const newEmail = inputEmail.value;
			const password = passwordCheck.value;
			const oldEmail = oldEmailInput.value;
			const code = codeInput.value;

			try {
				const response = await fetch('{% url "api_member:email_change_form" code %}', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify({
						email: newEmail,
						password: password,
						oldEmail: oldEmail,
						verification_code: code,
					})
				});

				const data = await response.json();
				messageDiv.textContent = data.message;
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert ' + (data.status === 'success' ? 'alert-success' : 'alert-danger');

				if (data.status === 'success') {
					setTimeout(() => {
						window.location.href = '{% url "member:login" %}';
					}, 5000);
				}
			} catch (error) {
				console.error('Error:', error);
				messageDiv.textContent = '發生錯誤，請稍後再試。';
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert alert-danger';
			}
		});
	</script>
</body>
</html> 

member/templates/member/email_reconfirm.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>郵箱重設／Email Reset</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media"> 
	
	{% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
	

    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">
	
</head> 

<body class="app app-reset p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'member:reset' %}"><img class="logo-icon me-2" src="{% static 'member\images\app-logo.svg' %}" alt="logo"></a></div>
					
					<h2 class="auth-heading text-center mb-4">Email Reset／郵箱重設</h2>

					<div class="auth-intro mb-4 text-center">請於下方輸入您的新郵箱與密碼，以便為您重設。<br>
						Enter your new email and password below.<br> We'll reset you a new email.</div>
					<div class="auth-form-container text-left">
						
						<form class="auth-form resetpass-form" id="resetEmailForm" action="{% url 'api_member:reconfirm_email' token %}" method="POST">
							{% csrf_token %}                  
							<div class="email mb-3">
								<input type="hidden" id="codeInput" value="{{ request.GET.code }}">
								<input type="hidden" id="emailInput" value="{{ request.GET.email }}">
								<label class="sr-only" for="InputEmail">新郵箱：</label>
								<input id="InputEmail" name="email" type="email" class="form-control login-email" placeholder="新郵箱" required>
								<label class="sr-only" for="PasswordCheck">註冊密碼：</label>
								<input id="PasswordCheck" name="password1" type="password" class="form-control login-password1" placeholder="註冊密碼" minlength="8" required>

								<div id="emailHelp" class="alert alert-warning" style="display: none;"></div>
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" id="submitCheck" class="btn app-btn-primary btn-block theme-btn mx-auto">修改郵箱</button>
							</div>
						</form>

						<div id="message" class="alert" style="display: none;"></div>

						<div class="auth-option text-center pt-5"><a class="app-link" href="{% url 'member:login' %}" >Log in／登入</a> <span class="px-2">|</span> <a class="app-link" href="{% url 'member:signup' %}" >Sign up／註冊</a></div>
					</div><!--//auth-form-container-->


			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-3.jpg' %}'); background-size: cover;">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->

	<script>
		const resetEmailForm = document.querySelector('#resetEmailForm');
		const messageDiv = document.querySelector('#message');
		const inputEmail = document.querySelector('#InputEmail');
		const passwordCheck = document.querySelector('#PasswordCheck');
		const emailHelp = document.querySelector('#emailHelp');

		resetEmailForm.addEventListener('submit', async function(e) {
			e.preventDefault();

			const confirmEmail = inputEmail.value;
			const confirmPassword = passwordCheck.value;
			const code = document.querySelector('#codeInput').value;
			const email = document.querySelector('#emailInput').value;

			if (email == confirmEmail) {
				emailHelp.textContent = '郵箱已存在，請重新輸入。';
				emailHelp.style.display = 'block';
				return;
			}

			const response = await fetch('{% url "api_member:reconfirm_email" token %}', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'X-CSRFToken': '{{ csrf_token }}'
				},
				body: JSON.stringify({
					password: confirmPassword,
					code: code,
					newEmail: confirmEmail
				})
			});

			const data = await response.json();

			messageDiv.textContent = data.message;
			messageDiv.style.display = 'block';
			messageDiv.className = 'alert ' + (data.status === 'success' ? 'alert-success' : 'alert-danger');

			if (data.status === 'success') {
				setTimeout(() => {
					window.location.href = '{% url "member:login" %}';
				}, 5000);
			}
		});
	</script>
</body>
</html> 