ACGN_Project/urls.py
from django.contrib import admin
from django.urls import path, include # 導入個人應用程式
from django.conf import settings
from django.conf.urls.static import static

from . import views  # 導入專案的 views.py(自己手動建的)

urlpatterns = [
    # 預設路徑(http://127.0.0.1:8000/)時
    # 去找專案資料夾下的views.py(自己手動建的)的 index 函數
    # path('', views.index),

    # 原路徑 - 後台管理頁面'登入頁面'
    # path('admin/', admin.site.urls, name='admin'),

    # http://127.0.0.1:8000/<str:template_name>.html 
    # 以確保操作index時其餘頁面都能正常連結到
    path('<str:template_name>.html', views.render_template, name='render_template'),
    
    # http://127.0.0.1:8000/Example_APP/ 
    # 假設我們各自導入自己的應用程式(Example_APP)個人操作的模樣
    path('Example_APP/', include('Example_APP.urls')),

    # admin-APP (後台管理者)
    # http://127.0.0.1:8000/admin/
    path('admin/', include('admins.urls')), # 包含 admin 的 URL
    # http://127.0.0.1:8000/admin/
    path('api_admin/', include('api_admin.urls')), # 包含 api_admin 的 URL

    # Member-APP (後台會員)
    # http://127.0.0.1:8000/admin/member/ 
    path('admin/member/', include('member.urls')), # 包含 member 的 URL
    # http://127.0.0.1:8000/admin/api_member/ 
    path('admin/api_member/', include('api_member.urls')),  # 包含 api_member 的 URL
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admins/urls.py
from django.urls import path
from . import views  # 導入視圖

app_name = "admins"
urlpatterns = [
    # 後台 管理者- 登入 首頁 
    # http://127.0.0.1:8000/admin
    path('', views.login, name="login"),
    # http://127.0.0.1:8000/admin/index
    path('index', views.index, name="index"),


    # 後台 管理者- 登出 註冊 重置密碼 
    # http://127.0.0.1:8000/admin/logout
    path('logout/', views.logout, name="logout"),
    # http://127.0.0.1:8000/admin/signup
    path('signup/', views.signup, name="signup"),
    # http://127.0.0.1:8000/admin/reset
    path('reset/', views.reset, name="reset"),

]

api_admin/urls.py
from django.urls import path
from . import views  # 導入視圖

app_name = "api_admin"
urlpatterns = [
    # http://127.0.0.1:8000/api_admin/signup
    path('signup/', views.signup, name="signup"),
    # http://127.0.0.1:8000/api_admin/reset
    path('reset/', views.reset, name="reset"),

]

admins/templates/admins/index.html
{% extends '[BASE]ALL.html' %}

{% load static %}

{% block app_css %}
<style>

</style>
{% endblock %}


{% block app_title %}
<h3>ACGN-後台管理</h3>
{% endblock %}


{% block app_content %}
<div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
    <div class="inner">
        <div class="app-card-body p-3 p-lg-4">
            <h3 class="mb-3">Welcome 歡迎回來 , {{ auth.superuser_name }}管理者 !</h3>
            <div class="row gx-5 gy-3">
                <div class="col-12 col-lg-9">
                    <div>這是 ACGN_後台管理頁面...</div>
                    <div>1...</div>
                    <div>2...</div>
                    <div>3...</div>
                    <div>4...</div>
                    <div>5...</div>
                    <div>6...</div>
                </div><!--//col-->
                <div class="col-12 col-lg-3">
                </div><!--//col-->
            </div><!--//row-->
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div><!--//app-card-body-->
        
    </div><!--//inner-->
</div><!--//app-card-->
{% endblock %}
                              
            <footer class="app-footer">
                <div class="container text-center py-3">
                    <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
                    <!-- 用人家免費的留頁腳尊重一下 -->
                <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
                   
                </div>
            </footer><!--//app-footer-->
            
        </div><!--//app-wrapper-->


<!-- Javascript -->
<!-- FontAwesome JS -->
<script defer src="{% static 'plugins/fontawesome/js/all.min.js' %}"></script>
<script src="{% static 'plugins/popper.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Charts JS -->
<script src="{% static 'plugins/chart.js/chart.min.js' %}"></script>
<script src="{% static 'js/index-charts.js' %}"></script>

<!-- Page Specific JS -->
<script src="{% static 'js/app.js' %}"></script>
{% block app_script %}

{% endblock %}
    </body>
</html>

admins/templates/admins/login.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>後台管理頁面／Log in</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    

    {% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">

</head> 

<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'admins:login' %}"><img class="logo-icon me-2" src="{% static 'member/images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in／後台管理頁面</h2>
			        <div class="auth-form-container text-start">
						<form class="auth-form login-form" method="post" enctype="multipart/form-data" action="{% url 'admins:login' %}">
							{% csrf_token %}
							{% if messages %}
							    {% for message in messages %}
							        <div class="alert alert-danger" role="alert">
							            {{ message }}
							        </div>
							    {% endfor %}
							{% endif %}
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">電子郵箱</label>
								<input id="signin-email" name="email" type="email" class="form-control signin-email" placeholder="電子郵箱" required="required" {% if remembered_email %}value="{{ remembered_email }}"{% endif %}>
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">密碼</label>
								<input id="signin-password" name="password" type="password" class="form-control signin-password" placeholder="密碼" required="required">
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" name="remember_me" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
												記住我
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="{% url 'admins:reset' %}">忘記後台密碼?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">登入管理頁面</button>
							</div>
						</form>
						
						{% if message %}
						<div class="auth-message mt-3">
							<div class="alert alert-info">{{ message }}</div>
						</div>
						{% endif %}
						
						<div class="auth-option text-center pt-5">沒有後台帳號? <a class="text-link" href="{% url 'admins:signup' %}" >Sign up／使用者註冊</a></div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-green.jpg' %}'); background-size: cover;">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->


</body>
</html> 

admins/templates/admins/reset.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>忘記後台密碼／Forgot Password</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media"> 
	
	{% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
	

    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">
	
</head> 

<body class="app app-reset p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'admins:reset' %}"><img class="logo-icon me-2" src="{% static 'member\images\app-logo.svg' %}" alt="logo"></a></div>
					
					<h2 class="auth-heading text-center mb-4">Forgot Password<br>忘記後台密碼</h2>

					<div class="auth-intro mb-4 text-center">請於下方輸入您的電子郵箱，<br>與您的新密碼，以便您快速重設密碼。<br>
						Enter your email address and new password below. You can easily create a new password.</div>
					<div class="auth-form-container text-left">
						<form class="auth-form resetpass-form" method="POST" id="resetForm" enctype="multipart/form-data" action="{% url 'api_admin:reset' %}">
							{% csrf_token %}                  
							<div class="email mb-3">
								<label class="sr-only" for="email">電子郵箱</label>
								<input id="email" name="email" type="email" class="form-control login-email" placeholder="電子郵箱" required>
								<label class="sr-only" for="InputPassword">新密碼</label>
								<input id="InputPassword" name="password" type="password" class="form-control login-email" placeholder="新密碼" minlength="8" required>
								<label class="sr-only" for="PasswordCheck">確認新密碼</label>
								<input id="PasswordCheck" name="password1" type="password" class="form-control login-email" placeholder="確認新密碼" minlength="8" required>
							</div><!--//form-group-->
							<div id="message" class="alert" style="display: none;"></div>
							<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">確認送出</button>
						</form>
						
						
						<div class="auth-option text-center pt-5"><a class="app-link" href="{% url 'admins:login' %}" >Log in／登入</a> <span class="px-2">|</span> <a class="app-link" href="{% url 'admins:signup' %}" >Sign up／註冊</a></div>
					</div><!--//auth-form-container-->


			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-3.jpg' %}'); background-size: cover;">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->


	<script>
		const form = document.querySelector("#resetForm");
		const messageDiv = document.querySelector('#message');
		
		function isValidPassword(password) {
			// 檢查密碼長度
			if (password.length < 8) {
				return false;
			}
			// 檢查是否包含至少一個字母和一個數字
			const hasLetter = /[a-zA-Z]/.test(password);
			const hasNumber = /\d/.test(password);
			return hasLetter && hasNumber;
		}

		form.addEventListener('submit', async (event) => {
			event.preventDefault();

			const email = document.querySelector("#email").value;
        	const password = document.querySelector('#InputPassword').value;
        	const confirmPassword = document.querySelector('#PasswordCheck').value;
			
			if (!isValidPassword(password)) {
				messageDiv.textContent = '密碼必須至少8個字符，並包含字母和數字。';
				messageDiv.className = 'alert alert-danger';
				messageDiv.style.display = 'block';
				return;
			}

			if (password !== confirmPassword) {
				messageDiv.textContent = '密碼不一致，請重新輸入。';
				messageDiv.className = 'alert alert-danger';
				messageDiv.style.display = 'block';
				return;
			}

			try {
				const response = await fetch('/api_admin/reset/', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify({
						email: email,
						password: password,
						password1: confirmPassword
					})
				});

				const data = await response.json();
				messageDiv.textContent = data.message;
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert ' + (data.status === 'success' ? 'alert-success' : 'alert-danger');
		
				if (data.status === 'success') {
					setTimeout(() => {
						window.location.href = "{% url 'admins:login' %}";
					}, 5000);
				}
			} catch (error) {
				console.error('Error:', error);
				messageDiv.textContent = '發生錯誤，請稍後再試。';
				messageDiv.style.display = 'block';
				messageDiv.className = 'alert alert-danger';
			}
		});
	</script>
</body>
</html> 

admins/templates/admins/signup.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <title>管理者註冊／Sign up</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    
    {% load static %}
    <link rel="shortcut icon" href="{% static 'member/favicon.ico' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'member/scripts/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'member/styles/portal.css' %}">
</head> 

<body class="app app-signup p-0">    	
    <div class="row g-0 app-auth-wrapper">
        <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
            <div class="d-flex flex-column align-content-end">
                <div class="app-auth-body mx-auto">	
                    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'admins:signup' %}"><img class="logo-icon me-2" src="{% static 'member/images/app-logo.svg' %}" alt="logo"></a></div>
                    <h2 class="auth-heading text-center mb-4">Sign up／管理者註冊</h2>					
    
                    <div class="auth-form-container text-start mx-auto">
                        <form class="auth-form auth-signup-form" method="POST" enctype="multipart/form-data" id="signupForm" action="{% url 'api_admin:signup' %}">  
                            {% csrf_token %}
                            <div class="email mb-3">
                                <label class="sr-only" for="InputName">姓名</label>
                                <input id="InputName" name="auth_username" type="text" class="form-control signup-name" placeholder="姓名*" required minlength="2" maxlength="10">
                                <small class="form-text text-muted">請輸入2-10個字符</small>
                            </div>
                            <div class="email mb-3">
                                <label class="sr-only" for="InputEmail">電子郵箱</label>
                                <input id="InputEmail" name="auth_useremail" type="email" class="form-control signup-email" placeholder="電子郵箱*" required>
                                <small class="form-text text-muted">請輸入有效的電子郵箱地址</small>
                            </div>
                            <div class="password mb-3">
                                <label class="sr-only" for="InputPassword">密碼</label>
                                <input id="InputPassword" name="password" type="password" class="form-control signup-password" placeholder="密碼*" required minlength="8">
                                <small class="form-text text-muted">密碼至少需要8個字符，英文(不分大小寫)+數字</small>
                            </div>
                            <div class="password mb-3">
                                <label class="sr-only" for="ConfirmPassword">確認密碼</label>
                                <input id="ConfirmPassword" name="confirm_password" type="password" class="form-control signup-password" placeholder="確認密碼*" minlength="8" required>
                            </div>
                            <div id="passwordHelp" class="alert alert-warning" style="display: none;"></div>
                            <div class="text-center">
                                <button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto" id="buttonSubmit">使用者註冊</button>
                            </div>
                        </form><!--//auth-form-->
                        
                        <div class="auth-option text-center pt-5">已經有後台帳號? <a class="text-link" href="{% url 'admins:login' %}" >Log in／登入後台</a></div>
                    </div><!--//auth-form-container-->	
                </div><!--//auth-body-->
            
                <footer class="app-auth-footer">
                    <div class="container text-center py-3">
                        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
                    </div>
                </footer><!--//app-auth-footer-->	
            </div><!--//flex-column-->   
        </div><!--//auth-main-col-->
        <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col" style="background-image: url('{% static 'member/images/background-car.jpg' %}'); background-size: cover;">
            <div class="auth-background-holder">
            </div>
            <div class="auth-background-mask"></div>
            <div class="auth-background-overlay p-3 p-lg-5">
                <div class="d-flex flex-column align-content-end h-100">
                    <div class="h-100"></div>
                    <div class="overlay-content p-3 p-lg-4 rounded">
                        <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
                        <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
                    </div>
                </div>
            </div><!--//auth-background-overlay-->
        </div><!--//auth-background-col-->
    </div><!--//row-->

    <!-- Alert 提示區域 -->
    <div id="alertMessage" class="alert alert-warning" style="display: none; position: fixed; top: 20px; left: 50%; transform: translateX(-50%); z-index: 1000;"></div>
	{% if messages %}
	<ul class="messages">
    {% for message in messages %}
    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
	</ul>
{% endif %}

<script>
    const alertDiv = document.querySelector('#alertMessage');
    const form = document.querySelector('#signupForm');

    function isValidPassword(password) {
			// 檢查密碼長度
			if (password.length < 8) {
				return false;
			}
			// 檢查是否包含至少一個字母和一個數字
			const hasLetter = /[a-zA-Z]/.test(password);
			const hasNumber = /\d/.test(password);
			return hasLetter && hasNumber;
		}

    form.addEventListener('submit', async (event) => {
        event.preventDefault();

        const formData = new FormData(form);
        const password = document.querySelector('#InputPassword').value;
        const confirmPassword = document.querySelector('#ConfirmPassword').value;

        if (!isValidPassword(password)) {
            alertDiv.textContent = '密碼必須至少8個字符，並包含字母和數字。';
            alertDiv.className = 'alert alert-danger';
            alertDiv.style.display = 'block';
            return;
        }

			if (password !== confirmPassword) {
				alertDiv.textContent = '密碼不一致，請重新輸入。';
				alertDiv.className = 'alert alert-danger';
				alertDiv.style.display = 'block';
				return;
			}

        try {
            const response = await fetch('/api_admin/signup/', {
                method: 'POST',
                body: formData
            });
            const data = await response.json();
            alertDiv.textContent = data.message;
            alertDiv.style.display = 'block';
            alertDiv.className = 'alert ' + (data.success ? 'alert-success' : 'alert-danger');

            if (data.success) {
                setTimeout(() => {
                    window.location.href = data.redirect_url; // 使用返回的重定向 URL
                }, 5000);
            }
        } catch (error) {
            console.error('Error:', error);
            messageDiv.textContent = '發生錯誤，請稍後再試。';
            messageDiv.style.display = 'block';
            messageDiv.className = 'alert alert-danger';
        }
    });
</script>
</body>
</html>